# Generated by Django 5.2.15 on 2026-08-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
