# Generated by Django 5.2.15 on 2026-08-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_donor_last_donation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
