# Generated by Django 5.2.15 on 2026-09-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_admincredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
